version: '3.6'

services:
  application:
    build: .
    container_name: application
    ports:
      - 8080:8080
    restart: always

  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: application:8080
      SERVERNAME: application
    ports:
      - "80:80"
      - "443:443"