version: '3.6'

services:
  application:
    build: .
    container_name: application
    ports:
      - 8080:8080
    restart: always

  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: application
      SERVERNAME: test.example.com
    ports:
      - "80:80"
      - "443:443"